@startuml

title __MODEL's Class Diagram__\n

  package com.deloitte.digital {
    package com.deloitte.digital.Model {
      class Activity {
          - title : String
          - duration : long
          + Activity()
          + getTitle()
          + setTitle()
          + getDuration()
          + setDuration()
          + toString()
      }
    }
  }
  

  package com.deloitte.digital {
    package com.deloitte.digital.Model {
      class DigitalDaySchedule {
          ~ digitalDayActivities : List<Activity>
          ~ totalActivitiesDuration : long
          ~ teamSize : int
          ~ logger : Logger
          + setTotalActivitiesDuration()
          + setTeamSize()
          + setDigitalDayActivities()
          + getDigitalDayActivities()
          + getTeamSize()
      }
    }
  }
  

  package com.deloitte.digital {
    package com.deloitte.digital.Model {
      interface Schedule {
          {static} + START_OF_DAY : LocalTime
          {static} + MIN_END_OF_DAY : LocalTime
          {static} + MAX_END_OF_DAY : LocalTime
          {static} + LUNCH_START : LocalTime
          {static} + LUNCH_END : LocalTime
          {static} + SPRINT : String
          {static} + UNIT : ChronoUnit
          {static} + MANDATORY_END_ACTIVITY : String
          {static} + MANDATORY_END_ACTIVITY_DURATION : long
          + getPreLunchDuration()
          + getPostLunchMaxDuration()
          + getPostLunchMinDuration()
          + getMinimumTotalActivityTimePerDay()
      }
    }
  }
  

  package com.deloitte.digital {
    package com.deloitte.digital.Model {
      class Timetable {
          ~ name : String
          ~ duration : long
          ~ startTime : LocalTime
          {static} ~ timeColonPattern : String
          {static} ~ timeColonFormatter : DateTimeFormatter
          + Timetable()
          + toString()
      }
    }
  }
  

  DigitalDaySchedule -up-|> Schedule


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
